crina_site_management_site_list:
    pattern:  /list-sites/{page}
    defaults: { _controller: CrinaSiteManagementSiteBundle:Default:list, page: 1 }
    
crina_site_management_site_edit:
    pattern:  /edit-site/{id}
    defaults: { _controller: CrinaSiteManagementSiteBundle:Default:edit, id: null }
    
crina_site_management_site_delete:
    pattern: /delete-site/{id}
    defaults: { _controller: CrinaSiteManagementSiteBundle:Default:delete, id: null }