parameters:
#    crina_site_management_site.example.class: Crina\SiteManagement\SiteBundle\Example

services:
#    crina_site_management_site.example:
#        class: %crina_site_management_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
